In [28]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install pydub
!{sys.executable} -m pip install pandas

Requirement already satisfied: pydub in /Users/joellarwood/opt/miniconda3/lib/python3.7/site-packages (0.24.0)
Requirement already satisfied: pandas in /Users/joellarwood/opt/miniconda3/lib/python3.7/site-packages (1.0.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /Users/joellarwood/opt/miniconda3/lib/python3.7/site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /Users/joellarwood/opt/miniconda3/lib/python3.7/site-packages (from pandas) (2020.1)
Requirement already satisfied: numpy>=1.13.3 in /Users/joellarwood/opt/miniconda3/lib/python3.7/site-packages (from pandas) (1.18.4)
Requirement already satisfied: six>=1.5 in /Users/joellarwood/opt/miniconda3/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas) (1.14.0)
ERROR: unknown command "rpy2"

In [145]:
from pydub import AudioSegment
from pydub.utils import make_chunks
import pandas as pd
import os

## Selecting songs to split

The file `eerola_song_ratings.csv` contains the song ratings for the whole songs. I want to select the songs that seem most appropriate to split. I need to keep the songs where the target is Anger, Fear, Happy, or Sad

In [128]:
ratings = pd.read_csv("eerola_song_ratings.csv")

ratings.head(3)

,Number,Valence,Energy,Tension,Anger,Fear,Happy,Sad,Tender,Beauty,Liking,TARGET,soundtrack,link
0,1,2.56,7.73,8.38,6.39,4.40,1.21,1.75,1.01,4.71,4.97,ANGER_HIGH,Lethal weapon 3,227
1,2,2.50,8.21,8.56,5.76,5.93,1.09,1.60,1.10,4.57,4.79,ANGER_HIGH,The Rainmaker,124
2,3,2.92,8.21,8.17,6.31,4.06,1.31,1.55,1.01,4.45,5.06,ANGER_HIGH,The Alien Trilogy,125

## Song selection and splitting

For each song the target emotion needs to have the highest rating

### Anger

Select songs that meet criterea

In [97]:
anger = ratings[ratings['TARGET'].str.contains("ANGER")]

# I need the anger rating to be higher than the ratings for all othe emotions 

anger = anger.query('Anger > Fear')

anger = anger.assign(dist = anger["Anger"] - anger["Fear"]) 

anger = anger[anger.dist > .5]

,Number,Valence,Energy,Tension,Anger,Fear,Happy,Sad,Tender,Beauty,Liking,TARGET,soundtrack,link,dist
0,1,2.56,7.73,8.38,6.39,4.40,1.21,1.75,1.01,4.71,4.97,ANGER_HIGH,Lethal weapon 3,227,1.99
2,3,2.92,8.21,8.17,6.31,4.06,1.31,1.55,1.01,4.45,5.06,ANGER_HIGH,The Alien Trilogy,125,2.25
3,4,2.88,6.75,7.98,5.42,4.51,1.19,2.10,1.06,4.00,4.35,ANGER_HIGH,Cape Fear,168,0.91
4,5,3.08,6.83,7.50,6.13,4.24,1.07,2.96,1.07,5.08,5.35,ANGER_HIGH,The Fifth Element,239,1.89
7,8,4.00,6.21,7.08,3.81,3.19,1.19,5.15,1.37,6.00,5.79,ANGER_MODERATE,Man of Galilee CD1,114,0.62

The songs that meet criterea are:  
* 1  
* 3   
* 4   
* 5   
* 8   
    
These will be placed into `full_songs/anger` and I will export snippets to `/snippets/`

In [144]:
anger_path = os.path.join(os.getcwd(), "full_songs/anger")
print(anger_path)
anger_songs = os.listdir(anger_path)
print(anger_songs)

/Users/joellarwood/Desktop/git/alexithymia_cross_modal_emotion/song_processing/full_songs/anger
['008.mp3', '001.mp3', '003.mp3', '004.mp3', '005.mp3']

In [156]:
#for filename in os.listdir(anger_path): 
filepath = os.path.join(anger_path, filename)
song = AudioSegment.from_file(filepath, "mp3")
chunks = make_chunks(song, 1000)
for i, chunk in enumerate(chunks): 
    chunk_name = "chunk{0}.mp3".format(i)
    print ("exporting", chunk_name)
    chunk.export(chunk_name, format="mp3")

exporting chunk0.mp3
exporting chunk1.mp3
exporting chunk2.mp3
exporting chunk3.mp3
exporting chunk4.mp3
exporting chunk5.mp3
exporting chunk6.mp3
exporting chunk7.mp3
exporting chunk8.mp3
exporting chunk9.mp3
exporting chunk10.mp3
exporting chunk11.mp3
exporting chunk12.mp3
exporting chunk13.mp3
exporting chunk14.mp3
exporting chunk15.mp3

In [ ]:
myaudio = AudioSegment.from_file("myAudio.wav" , "wav") 
chunks = make_chunks(myaudio, 1000) #Make chunks of one sec

#Export all of the individual chunks as wav files

for i, chunk in enumerate(chunks):
    chunk_name = "chunk{0}.wav".format(i)
    print "exporting", chunk_name
    chunk.export(chunk_name, format="wav")

### Fear

In [106]:
fear = ratings[ratings['TARGET'].str.contains("FEAR")]

# I need the anger rating to be higher than the ratings for all othe emotions 

fear = fear.query('Fear > Anger')

fear = fear.assign(dist = fear["Fear"] - fear["Anger"]) 

fear = fear[fear.dist > .5]

fear_tracks = fear["Number"].tolist()

fear

,Number,Valence,Energy,Tension,Anger,Fear,Happy,Sad,Tender,Beauty,Liking,TARGET,soundtrack,link,dist
10,11,2.38,6.38,8.33,2.79,7.42,1.09,1.60,1.07,3.58,4.37,FEAR_HIGH,Batman Returns,219,4.63
11,12,3.60,7.42,8.06,2.28,6.12,1.28,1.57,1.27,4.65,4.99,FEAR_HIGH,JFK,266,3.84
12,13,3.19,7.10,8.15,2.13,6.34,1.31,1.21,1.06,4.43,5.39,FEAR_HIGH,JFK,320,4.21
13,14,2.31,7.48,8.54,2.61,6.79,1.07,1.36,1.01,3.44,3.82,FEAR_HIGH,The Alien Trilogy,157,4.18
14,15,2.31,6.13,8.10,2.00,6.52,1.04,1.70,1.06,4.08,4.22,FEAR_HIGH,Hannibal,313,4.52
15,16,4.21,7.56,7.79,1.88,4.58,1.37,2.10,1.22,4.22,5.00,FEAR_MODERATE,Running Scared,173,2.70
16,17,3.02,4.58,7.75,1.75,6.25,1.10,1.75,1.16,4.35,4.55,FEAR_MODERATE,The Fifth Element,321,4.50
18,19,4.58,4.83,6.81,1.34,2.93,1.49,3.69,2.12,4.95,5.18,FEAR_MODERATE,Lethal weapon 3,325,1.59

In [127]:
happy = ratings[ratings["TARGET"].str.contains("HAPPY")]

happy = happy.query('Happy > Sad')

happy = happy.query("Happy > Tender")

happy = happy.assign(dist = happy["Happy"] - happy["Sad"])

happy = happy[happy.dist > .5]

happy_track = happy["Number"].tolist()

happy

,Number,Valence,Energy,Tension,Anger,Fear,Happy,Sad,Tender,Beauty,Liking,TARGET,soundtrack,link,dist
20,21,8.00,7.77,4.02,1.00,1.09,6.63,1.12,2.19,5.79,5.92,HAPPY_HIGH,The Rainmaker,3,5.51
21,22,7.56,8.35,5.06,1.33,1.18,6.81,1.30,1.51,5.53,5.36,HAPPY_HIGH,Batman,250,5.51
22,23,8.27,8.54,4.46,1.04,1.03,8.21,1.10,1.45,4.35,4.85,HAPPY_HIGH,Shallow Grave,1,7.11
23,24,7.96,8.63,5.94,1.27,1.12,6.94,1.09,1.27,4.57,4.82,HAPPY_HIGH,Man of Galilee CD1,4,5.85
24,25,7.67,7.42,4.15,1.09,1.12,6.28,1.58,2.22,5.89,5.75,HAPPY_HIGH,Oliver Twist,192,4.70
25,26,6.90,5.25,4.21,1.04,1.52,4.66,2.16,4.34,6.19,5.83,HAPPY_MODERATE,The Omen,270,2.50
26,27,7.75,8.08,4.77,1.09,1.24,6.27,1.67,2.30,6.32,6.65,HAPPY_MODERATE,Oliver Twist,246,4.60

### Sad

In [122]:
sad = ratings[ratings["TARGET"].str.contains("SAD")]

sad = sad.query("Sad > Tender")

sad = sad.assign(dist = sad["Sad"] - sad["Tender"])

sad = sad[sad.dist > .5]

sad

,Number,Valence,Energy,Tension,Anger,Fear,Happy,Sad,Tender,Beauty,Liking,TARGET,soundtrack,link,dist
30,31,5.02,3.19,3.65,1.10,1.69,1.25,6.78,3.58,6.86,5.96,SAD_HIGH,The English Patient,32,3.20
31,32,4.04,3.67,5.33,1.99,3.07,1.09,5.15,1.94,5.80,5.28,SAD_HIGH,Running Scared,36,3.21
32,33,4.38,2.48,3.27,1.07,1.78,1.12,7.18,3.03,6.73,5.83,SAD_HIGH,The Portait of a Lady,288,4.15
33,34,4.85,3.52,4.17,1.13,1.39,1.40,6.12,3.15,6.25,5.98,SAD_HIGH,Big Fish,39,2.97
34,35,4.25,5.58,6.25,2.39,2.22,1.66,5.73,2.79,6.43,5.71,SAD_HIGH,Man of Galilee CD1,40,2.94
35,36,5.13,2.52,3.81,1.10,2.19,1.34,5.21,2.43,5.43,5.26,SAD_MODERATE,Angel Heart,274,2.78
36,37,4.79,3.88,5.25,1.16,3.27,1.72,4.18,3.04,6.36,5.98,SAD_MODERATE,Batman,297,1.14
37,38,4.73,2.79,4.60,1.09,2.16,1.15,4.07,2.70,5.45,4.90,SAD_MODERATE,Dracula,276,1.37
39,40,5.58,3.67,4.40,1.01,1.55,2.09,5.33,4.46,6.66,5.78,SAD_MODERATE,The English Patient,30,0.87

In [10]:
path = os.getcwd()

In [11]:
print(path)

/Users/joellarwood/Desktop/git/alexithymia_cross_modal_emotion/song_processing

# Setting up directories where full songs are stored

I want to set the directory that contains the songs so I cna loop through them and create 1 second clips (so 15 clips per song over all the songs in the folder). 

I have named the clips in the structure of  `emotion_clip`. They will be exported to a folder `song_processing/1sec_clips` wiht the naming strucutre `emotion_clip_startsec`

In [5]:
full_song_path = os.path.join(path, "song_processing/full_songs")

In [6]:
print(full_song_path)

/Users/joellarwood/Desktop/git/alexithymia_cross_modal_emotion/song_processing/song_processing/full_songs

In [7]:
print(os.listdir(full_song_path))

FileNotFoundError: [Errno 2] No such file or directory: '/Users/joellarwood/Desktop/git/alexithymia_cross_modal_emotion/song_processing/song_processing/full_songs'